name: CI on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Thiết lập Node.js (nếu là project Node)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cài thư viện
        run: npm install

      - name: Chạy test
        run: npm test
